FROM docker.io/library/node:24-alpine

WORKDIR /app

RUN apk add --no-cache openjdk21-jre

COPY frontend/react/package*.json ./
RUN npm ci

EXPOSE 80

CMD ["sh", "-c", "npm ci && npm run generate:api && npm run dev -- --host 0.0.0.0 --port 80"]